version: '3'

services:
  backend_app:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        uid: ${UID}
    container_name: backed_app
    ports:
      - ${BACKEND_PORT}:80
    depends_on:
      - db
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ./backend:/var/www/backend
    networks:
      - app-network

  frontend_app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    container_name: frontend_app
    ports:
      - ${FRONTEND_PORT}:3000
    depends_on:
      - backend_app
    volumes:
      - ./frontend:/var/www/frontend
      - '/var/www/html/frontend/node_modules'
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./backend/db:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
